# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65679b52a5a0ab223f3542a2a0abdf34abf7177f74a27f34d3afce39cba80f891f1a08d448ded512002cc3f74e47c414b060f5219c953e2ceed2a20cc3d4d715

test:
  secret_key_base: 5b2cb58ac7c0652750c16083ad5a948df25b285ee74a2a7b3db4626a5c835b07d45fc97b2ca531c0322d569bf86f53e495c782bcf593b646ed388d6bda7bc3d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
